cart/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/',
         views.add_to_cart, name='add_to_cart'),
    path('reduce-cart-item/<int:cart_item_id>/',
         views.reduce_cart_item, name='reduce_cart_item'),
    path('remove-cart-item/<int:cart_item_id>/',
         views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
]

emart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('emart-secure-admin-login/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('user/', include('user.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store,
         name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail,
         name='product_detail'),
    path('search/', views.search, name='search'),
    path('submit-review/<int:product_id>',
         views.submit_review, name='submit_review'),
]

cart/models.py
from django.db import models


from store.models import Product, Variation
from user.models import User


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(
        Cart, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.product

    def sub_total(self):
        return self.product.price * self.quantity

store/models.py
from django.db import models
from django.db.models import Avg
from category.models import Category
from django.urls import reverse
from .choices import variation_category_choices
from user.models import User


class Product(models.Model):
    product_name = models.CharField(
        max_length=200, unique=True, db_collation='case_insensitive')
    slug = models.SlugField(unique=True, db_collation='case_insensitive')
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(blank=True, upload_to='photos/products')
    stock = models.IntegerField(default=0)
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_name

    def get_url(self):
        return reverse('product_detail', kwargs={'category_slug': self.category.slug, 'product_slug': self.slug})

    def get_average_rating(self):
        all_reviews = self.reviewrating_set.filter(
            status=True).aggregate(average=Avg('rating'))
        avg = 0
        if all_reviews['average'] is not None:
            avg = float(all_reviews['average'])
        return avg

    def get_reviews_count(self):
        return f'({self.reviewrating_set.filter(status=True).count()} reviews)'


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(
        max_length=100, choices=variation_category_choices)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(blank=True)
    rating = models.FloatField()
    ip_address = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class ProductGallery(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, default=None)
    image = models.ImageField(
        blank=True, upload_to='store/products_images', max_length=255)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'product gallery'
        verbose_name_plural = 'product gallery'

store/forms.py
from django import forms

from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from store.models import Product, Variation
from cart.models import Cart, CartItem
from core.utils import get_object_or_none, _cart_id


def add_to_cart(request, product_id):
    product = get_object_or_none(Product, id=product_id)
    requested_product_variations = []
    if request.method == 'POST':
        for item in request.POST:
            key = item
            value = request.POST[key]
            try:
                variation = Variation.objects.get(product=product,
                                                  variation_category__iexact=key, variation_value__iexact=value)
                requested_product_variations.append(variation)
            except:
                pass
    # if the user is authenticated, we don't need to filter using cart, we just use the user id
    if request.user.is_authenticated:
        cart_items = CartItem.objects.filter(
            user=request.user, product=product)
    else:
        # if user is not authenticated, we use cart to get cart items
        # get the cart using the cart id present in the session
        cart = get_object_or_none(Cart, cart_id=_cart_id(request))
        if not cart:
            cart = Cart.objects.create(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(
            product=product, cart=cart)

    # if the user is authenticated, we filter using user instead of cart
    if cart_items.exists():
        # note the cart item related to product may exist, but still we need to check if with the given variations, it still does exist
        existing_variations_list = []
        # cart_item_ids = []  # cart item ids
        for item in cart_items:
            current_item_variations = item.variations.all()
            existing_variations_list.append(list(current_item_variations))
            # cart_item_ids.append(item.id)

        if requested_product_variations in existing_variations_list:
            # the index of the variation is going to be the same as the index of item in cart_items since we are looping through
            # cart items and adding the variations as we loop
            index = existing_variations_list.index(
                requested_product_variations)
            # item_id = cart_item_ids[index]
            # item = CartItem.objects.get(product=product, id=item_id)
            item = cart_items[index]
            # increase cart item quantity
            item.quantity += 1
            item.save()
        else:
            if request.user.is_authenticated:
                cart_item = CartItem.objects.create(
                    product=product, quantity=1, user=request.user)
            else:
                # means this product exists, but with the given variations it does not exist in the cart, thus we add it to the cart
                cart_item = CartItem.objects.create(
                    product=product, quantity=1, cart=cart)
            if len(requested_product_variations) > 0:
                cart_item.variations.add(*requested_product_variations)
    else:
        # means this product does not exist in the cart, thus we add it to the cart
        if request.user.is_authenticated:
            cart_item = CartItem.objects.create(
                product=product, quantity=1, user=request.user)
        else:
            cart_item = CartItem.objects.create(
                product=product, quantity=1, cart=cart)
        if len(requested_product_variations) > 0:
            cart_item.variations.add(*requested_product_variations)

    return redirect('cart')


def reduce_cart_item(request, cart_item_id):
    cart_item = get_object_or_none(CartItem, id=cart_item_id)
    if cart_item:
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    return redirect('cart')


def remove_cart_item(request, cart_item_id):
    cart_item = get_object_or_none(CartItem, id=cart_item_id)
    if cart_item:
        cart_item.delete()

    return redirect('cart')


def cart(request, totals=0, quantity=0, cart_items=[]):
    tax = 0
    grand_totals = 0
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(
                user=request.user, is_active=True).order_by('-created_date')
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(
                cart=cart, is_active=True).order_by('-created_date')
        for cart_item in cart_items:
            totals += cart_item.product.price * cart_item.quantity
            quantity += cart_item.quantity

        # we charge VAT here at the rate of 16%
        tax = 16 * totals/100
        grand_totals = totals + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'cart_items': cart_items,
        'totals': totals,
        'quantity': quantity,
        'tax': tax,
        'grand_totals': grand_totals,
    }
    return render(request, 'store/cart.html', context)


@login_required(login_url='login_user')
def checkout(request, totals=0, quantity=0, cart_items=[]):
    tax = 0
    grand_totals = 0
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(
                user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            totals += cart_item.product.price * cart_item.quantity
            quantity += cart_item.quantity

        # we charge VAT here at the rate of 16%
        tax = 16 * totals/100
        grand_totals = totals + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'cart_items': cart_items,
        'totals': totals,
        'quantity': quantity,
        'tax': tax,
        'grand_totals': grand_totals,
    }
    return render(request, 'store/checkout.html', context=context)

store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404, HttpResponse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.db import connection
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Product, ReviewRating
from category.models import Category
from cart.models import CartItem
from orders.models import OrderProduct
from core.utils import get_object_or_none, _cart_id
from .forms import ReviewForm


def store(request, category_slug=None):
    category = None
    products = None
    if category_slug is not None:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(
            category=category, is_available=True).order_by('id')
    else:
        products = Product.objects.filter(is_available=True).order_by('id')

    products_count = products.count()
    paginator = Paginator(products, 10)
    page = request.GET.get('page')
    paged_products = paginator.get_page(page)
    context = {
        'products': paged_products,
        'products_count': products_count
    }
    return render(request, 'store/store.html', context)


def product_detail(request, category_slug, product_slug):
    single_product = get_object_or_none(
        Product, category__slug=category_slug, slug=product_slug)
    if not single_product:
        raise Http404
    in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(
        request), product=single_product).exists()

    try:
        user_has_purchased = OrderProduct.objects.filter(
            user=request.user, product=single_product).exists()
    except:
        user_has_purchased = False

    # get the reviews
    reviews = ReviewRating.objects.filter(product=single_product, status=True)

    context = {
        'single_product': single_product,
        'in_cart': in_cart,
        'user_has_purchased': user_has_purchased,
        'reviews': reviews
    }
    print(len(connection.queries))
    return render(request, 'store/product_detail.html', context)


def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET.get('keyword')
        if keyword:
            products = Product.objects.order_by(
                '-created_date').filter(description__icontains=keyword)
    context = {
        'products': products,
        'products_count': products.count()
    }
    return render(request, 'store/store.html', context)


@login_required
def submit_review(request, product_id):
    product_page_url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            review = ReviewRating.objects.get(
                user=request.user, product__id=product_id)
            form = ReviewForm(request.POST, instance=review)
            form.save()
            messages.success(
                request, 'Thank you. Your review has been updated')
            #  redirect to the same page
            return redirect(product_page_url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                new_review = ReviewRating()
                new_review.subject = form.cleaned_data['subject']
                new_review.review = form.cleaned_data['review']
                new_review.rating = form.cleaned_data['rating']
                new_review.ip_address = request.META.get('REMOTE_ADDR')
                new_review.product = Product.objects.get(id=product_id)
                new_review.user = request.user
                new_review.save()
                messages.success(
                    request, 'Thank you. Your review has been submitted')

                return redirect(product_page_url)

templates/store/cart.html
{% extends 'base.html' %} {% load static %} {% block content %}

<section class="section-content padding-y bg">
  <div class="container">
    <!-- ============================ COMPONENT 1 ================================= -->

    {% if not cart_items %}
    <h2 class="text-center">Your shopping cart is empty</h2>
    <br />
    <div class="text-center">
      <a href="{% url 'store' %}" class="btn btn-primary">Continue Shopping</a>
    </div>
    {% else %}
    <div class="row">
      <aside class="col-lg-9">
        <div class="card">
          <table class="table table-borderless table-shopping-cart">
            <thead class="text-muted">
              <tr class="small text-uppercase">
                <th scope="col">Product</th>
                <th scope="col" width="120">Quantity</th>
                <th scope="col" width="120">Price</th>
                <th scope="col" class="text-right" width="200"></th>
              </tr>
            </thead>
            <tbody>
              {% for item in cart_items %}
              <tr>
                <td>
                  <figure class="itemside align-items-center">
                    <div class="aside">
                      <img src="{{item.product.image.url}}" class="img-sm" />
                    </div>
                    <figcaption class="info">
                      <a
                        href="{{ item.product.get_url }}"
                        class="title text-dark"
                        >{{item.product.product_name}}</a
                      >
                      <p class="text-muted small">
                        {% if item.variations.all %}
                        <!-- prettier-ignore -->
                        {% for variation in item.variations.all %}
                        <!-- prettier-ignore -->
                        {{variation.variation_category | capfirst }} : {{variation.variation_value | capfirst }}
                        <br />
                        {% endfor %} {% endif %}
                      </p>
                    </figcaption>
                  </figure>
                </td>
                <td>
                  <!-- col.// -->
                  <div class="col">
                    <div class="input-group input-spinner">
                      <div class="input-group-prepend">
                        <form
                          action="{% url 'reduce_cart_item' item.id %}"
                          method="POST"
                        >
                          <!-- prettier-ignore -->
                          {% csrf_token %} {% for variation in item.variations.all %}
                          <input
                            type="hidden"
                            name="{{variation.variation_category | lower }}"
                            value="{{variation.variation_value | capfirst }}"
                          />
                          {% endfor %}
                          <button
                            class="btn btn-light"
                            id="button-plus"
                            type="submit"
                          >
                            <i class="fa fa-minus"></i>
                          </button>
                        </form>
                      </div>
                      <input
                        type="text"
                        class="form-control"
                        value="{{item.quantity}}"
                      />
                      <div class="input-group-append">
                        <form
                          action="{% url 'add_to_cart' item.product.id %}"
                          method="POST"
                        >
                          <!-- prettier-ignore -->
                          {% csrf_token %} {% for variation in item.variations.all %}
                          <input
                            type="hidden"
                            name="{{variation.variation_category | lower }}"
                            value="{{variation.variation_value | capfirst }}"
                          />
                          {% endfor %}
                          <button
                            class="btn btn-light"
                            type="submit"
                            id="button-minus"
                          >
                            <i class="fa fa-plus"></i>
                          </button>
                        </form>
                      </div>
                    </div>
                    <!-- input-group.// -->
                  </div>
                  <!-- col.// -->
                </td>
                <td>
                  <div class="price-wrap">
                    <var class="price">${{item.sub_total}}</var>
                    <small class="text-muted">
                      ${{item.product.price}} each
                    </small>
                  </div>
                  <!-- price-wrap .// -->
                </td>
                <td class="text-right">
                  <a
                    href="{% url 'remove_cart_item' item.id %}"
                    class="btn btn-danger"
                    onclick="return confirm('Are you sure you want to remove this item?')"
                  >
                    Remove</a
                  >
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- card.// -->
      </aside>
      <!-- col.// -->
      <aside class="col-lg-3">
        <div class="card">
          <div class="card-body">
            <dl class="dlist-align">
              <dt>Total price:</dt>
              <dd class="text-right">${{totals}}</dd>
            </dl>
            <dl class="dlist-align">
              <dt>Tax:</dt>
              <dd class="text-right">${{tax}}</dd>
            </dl>
            <dl class="dlist-align">
              <dt>Total:</dt>
              <dd class="text-right text-dark b">
                <strong>${{grand_totals}}</strong>
              </dd>
            </dl>
            <hr />
            <p class="text-center mb-3">
              <img src="{% static '/images/misc/payments.png' %}" height="26" />
            </p>
            <a href="{% url 'checkout' %}" class="btn btn-primary btn-block">
              Checkout
            </a>
            <a href="{% url 'store' %}" class="btn btn-light btn-block"
              >Continue Shopping</a
            >
          </div>
          <!-- card-body.// -->
        </div>
        <!-- card.// -->
      </aside>
      <!-- col.// -->
    </div>
    {% endif %}
    <!-- row.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
  </div>
  <!-- container .//  -->
</section>
{% endblock content %}

templates/store/product_detail.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section class="section-content padding-y bg">
  <div class="container">
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
      <div class="row no-gutters">
        <aside class="col-md-6">
          <article class="gallery-wrap">
            <div class="img-big-wrap main-image">
              <center><img src="{{single_product.image.url}}" /></center>
            </div>
            <!-- img-big-wrap.// -->
          </article>
          <ul class="thumbnails">
            <li>
              <a href="{{single_product.image.url}}" target="main-image"><img src="{{single_product.image.url}}" alt="product image" /></a>

              {% for imageItem in single_product.productgallery_set.all %}
              <a href="{{imageItem.image.url}}" target="main-image"><img src="{{imageItem.image.url}}" alt="product image" /></a>
              {% endfor %}
            </li>
          </ul>
          <!-- gallery-wrap .end// -->
        </aside>
        <main class="col-md-6 border-left">
          <form action="{% url 'add_to_cart' single_product.id %}" method="POST">
            {% csrf_token %}
            <article class="content-body">
              <h2 class="title">{{single_product.product_name}}</h2>
              {% include 'partials/rating.html' with ratingNumber=single_product.get_average_rating reviewsCount=single_product.get_reviews_count %}
              <div class="mb-3">
                <var class="price h4">${{single_product.price}}</var>
              </div>

              <p>{{single_product.description}}</p>

              <hr />
              <div class="row">
                <div class="item-option-select">
                  <h6>Choose Color</h6>
                  <select name="color" class="form-control" required>
                    <option value="" disabled selected>select color</option>
                    <!-- prettier-ignore -->
                    {% for color in single_product.variation_set.colors %}
                    <option value="{{color.variation_value | lower }}">{{color.variation_value | capfirst }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <!-- row.// -->
              <div class="row">
                <div class="item-option-select">
                  <h6>Choose Size</h6>
                  <select name="size" class="form-control" required>
                    <option value="" selected disabled>select size</option>
                    {% for size in single_product.variation_set.sizes %}
                    <option value="{{size.variation_value | lower }}">{{size.variation_value | capfirst }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <!-- row.// -->
              <hr />
              {% if single_product.stock <= 0 %}
              <h6 class="text-danger">Out of stock</h6>
              {% else %}
              <button type="'submit" class="btn btn-primary">
                <span class="text">Add to cart</span>
                <i class="fas fa-shopping-cart"></i>
              </button>
              {% endif %}
            </article>
          </form>
          <!-- product-info-aside .// -->
        </main>
        <!-- col.// -->
      </div>
      <!-- row.// -->
    </div>
    <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->

    <br />

    <div class="row">
      <div class="col-md-9">
        <form action="{% url 'submit_review' single_product.id %}" method="post">
          {% csrf_token %}
          <h5>Write your review</h5>
          <div>
            <!-- rating stars -->
            <label for="">How do you rate this product?</label>
            <br />
            <div class="rate">
              <input type="radio" name="rating" id="rating10" value="5" required /> <label for="rating10" title="5"></label>
              <input type="radio" name="rating" id="rating9" value="4.5" required /> <label for="rating9" title="4.5" class="half"></label>
              <input type="radio" name="rating" id="rating8" value="4" required /> <label for="rating8" title="4"></label>
              <input type="radio" name="rating" id="rating7" value="3.5" required /> <label for="rating7" title="3.5" class="half"></label>
              <input type="radio" name="rating" id="rating6" value="3" required /> <label for="rating6" title="3"></label>
              <input type="radio" name="rating" id="rating5" value="2.5" required /> <label for="rating5" title="2.5" class="half"></label>
              <input type="radio" name="rating" id="rating4" value="2" required /> <label for="rating4" title="2"></label>
              <input type="radio" name="rating" id="rating3" value="1.5" required /> <label for="rating3" title="1.5" class="half"></label>
              <input type="radio" name="rating" id="rating2" value="1" required /> <label for="rating2" title="1"></label>
              <input type="radio" name="rating" id="rating1" value="0.5" required /> <label for="rating1" title="0.5" class="half"></label>
            </div>
            Review Title:
            <input type="text" class="form-control" name="subject" />
            <br />
            Review:
            <textarea name="review" rows="4" class="form-control"></textarea>
            <br />
            {% if request.user.is_authenticated %} {% if user_has_purchased %}
            <input type="submit" value="Submit Review" class="btn btn-primary" />
            {% else %}
            <p>You must purchase this product to post a review</p>
            {% endif %} {% else %}
            <p>
              You must be logged in to post a review <span><a href="{% url 'login_user' %}">Login Now</a></span>
            </p>
            {% endif %}
          </div>
          <br />
          {% include 'partials/alerts.html' %}
        </form>
        <br />

        <header class="section-heading">
          <h3>Customer Reviews</h3>
          {% include 'partials/rating.html' with ratingNumber=single_product.get_average_rating reviewsCount=single_product.get_reviews_count %}
        </header>

        {% for reviewItem in reviews %}
        <article class="box mb-3">
          <div class="icontext w-100">
            <div class="text">
              <span class="date text-muted float-md-right">{{reviewItem.updated_at}} </span>
              <h6 class="mb-1">{{reviewItem.user.get_full_name}}</h6>
              {% include 'partials/rating.html' with ratingNumber=reviewItem.rating %}
            </div>
          </div>
          <!-- icontext.// -->
          <div class="mt-3">
            <h6>{{reviewItem.subject}}</h6>
            <p>{{reviewItem.review}}</p>
          </div>
        </article>
        {% endfor %}
      </div>
      <!-- col.// -->
    </div>
    <!-- row.// -->
  </div>
  <!-- container .//  -->
</section>

{% endblock %}