cart/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/',
         views.add_to_cart, name='add_to_cart'),
    path('reduce-cart-item/<int:cart_item_id>/',
         views.reduce_cart_item, name='reduce_cart_item'),
    path('remove-cart-item/<int:cart_item_id>/',
         views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
]

emart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('emart-secure-admin-login/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('user/', include('user.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('place-order/', views.place_order, name='place_order'),
    path('make-payment/', views.make_payment, name='make_payment'),
    path('order-complete/', views.order_complete, name='order_complete'),

]

orders/models.py
from django.db import models

from user.models import User
from .choices import order_status
from store.models import Product, Variation


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100)
    payment_method = models.CharField(max_length=100)
    amount_paid = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.payment_id


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(
        Payment, on_delete=models.SET_NULL, null=True, blank=True)
    order_number = models.CharField(max_length=20, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=50)
    address_line_1 = models.CharField(max_length=50)
    address_line_2 = models.CharField(max_length=50, blank=True, null=True)
    country = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    order_note = models.CharField(max_length=100, blank=True)
    order_total = models.FloatField(null=True)
    tax = models.FloatField(null=True)
    status = models.CharField(
        max_length=10, choices=order_status, default='New')
    ip = models.CharField(blank=True, max_length=20)
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'


class OrderProduct(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, null=True, blank=True)
    payment = models.ForeignKey(
        Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, null=True, blank=True)
    variations = models.ManyToManyField(
        Variation, blank=True)
    quantity = models.IntegerField()
    product_price = models.FloatField()
    ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.product_name

orders/forms.py
from django import forms

from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'phone', 'address_line_1',
                  'address_line_2', 'city', 'state', 'country', 'order_note']

orders/views.py
import json

from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.template.loader import get_template
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.core.mail import EmailMultiAlternatives
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode
from django.db import connection
from decouple import config
from django.contrib.auth.decorators import login_required

from cart.models import CartItem
import datetime

from .forms import OrderForm
from .models import Order, Payment, OrderProduct


def place_order(request):
    current_user = request.user
    # if the cart count is less than or equal to 0, then redirect back to store
    cart_items = CartItem.objects.filter(user=current_user)
    if cart_items.count() <= 0:
        return redirect('store')
    totals = 0
    tax = 0
    grand_totals = 0
    for item in cart_items:
        totals += item.product.price * item.quantity
    tax = 16 * totals/100
    grand_totals = totals + tax

    if request.method == 'POST':
        form = OrderForm(request.POST)
        print(form.is_valid())
        if form.is_valid():
            # get the cleaned data and store it
            new_order = Order()
            new_order.first_name = form.cleaned_data['first_name']
            new_order.last_name = form.cleaned_data['last_name']
            new_order.email = form.cleaned_data['email']
            new_order.phone = form.cleaned_data['phone']
            new_order.address_line_1 = form.cleaned_data['address_line_1']
            new_order.address_line_2 = form.cleaned_data['address_line_2']
            new_order.city = form.cleaned_data['city']
            new_order.state = form.cleaned_data['state']
            new_order.country = form.cleaned_data['country']
            new_order.order_note = form.cleaned_data['order_note']
            new_order.order_total = grand_totals
            new_order.tax = tax
            new_order.ip = request.META.get('REMOTE_ADDR')
            new_order.user = request.user
            new_order.save()

            # generate order number
            year_item = int(datetime.date.today().strftime('%Y'))
            day_item = int(datetime.date.today().strftime('%d'))
            month_item = int(datetime.date.today().strftime('%m'))
            date_obj = datetime.date(year_item, month_item, day_item)
            current_date = date_obj.strftime('%Y%m%d')
            order_number = f'{current_date}{new_order.id}'

            new_order.order_number = order_number
            new_order.save()

            context = {
                'order': new_order,
                'sub_totals': grand_totals - tax,
                'tax': tax,
                'grand_totals': grand_totals,
                'cart_items': cart_items,
            }

            return render(request, 'orders/make_payment.html', context)
        else:
            print(form.errors)
            return HttpResponse('error occurred')

    else:
        return redirect('checkout')


def make_payment(request):
    body = json.loads(request.body)
    order = Order.objects.get(
        user=request.user, is_ordered=False, order_number=body['orderID'])
    # store transaction details inside payment model
    payment = Payment(
        user=request.user,
        payment_id=body['transID'],
        payment_method=body['payment_method'],
        amount_paid=order.order_total,
        status=body['status'],
    )
    payment.save()

    order.payment = payment
    order.is_ordered = True
    order.save()

    # move the cart items to order products table
    cart_items = CartItem.objects.filter(user=request.user)
    for item in cart_items:
        order_product = OrderProduct()
        order_product.order = order
        order_product.payment = payment
        order_product.user = request.user
        order_product.product = item.product
        order_product.quantity = item.quantity
        order_product.product_price = item.product.price
        order_product.ordered = True
        order_product.save()

        cart_item = CartItem.objects.get(id=item.id)
        product_variation = cart_item.variations.all()
        order_product.variations.add(*product_variation)

        # reduce the quantity of sold products
        product = item.product
        product.stock -= item.quantity
        product.save()

    # clear the cart
    CartItem.objects.filter(user=request.user).delete()

    # send order received email to customer
    mail_subject = 'Thank you for your order.'
    html_content = get_template('orders/order_received_email.html')
    email_data = {
        'user': request.user,
        'order': order
    }

    body_text = f'Your order has been received'
    body_html = html_content.render({**email_data})
    to_email = request.user.email
    from_email = config('EMAIL_HOST_USER')

    send_email = EmailMultiAlternatives(
        mail_subject, body_text, from_email, [to_email])
    send_email.attach_alternative(body_html, "text/html")
    send_email.send(fail_silently=False)

    # send order number and transaction id to sendData method on frontend via JsonResponse
    data = {
        'order_number': order.order_number,
        'payment_id': payment.payment_id
    }

    return JsonResponse(data)


def order_complete(request):
    order_number = request.GET.get('order_number')
    payment_id = request.GET.get('payment_id')
    payment = Payment.objects.get(payment_id=payment_id)
    try:
        order = Order.objects.get(order_number=order_number, is_ordered=True)
        context = {
            'order': order,
            'payment': payment,
            'order_sub_total': round(order.order_total - order.tax)
        }
        return render(request, 'orders/order_complete.html', context)

    except (Payment.DoesNotExist, Order.DoesNotExist):
        return redirect('home')

templates/orders/make_payment.html
{% extends 'base.html' %} {% load static %} {% block content %}

<section class="section-content padding-y bg">
  <div class="container">
    <!-- ============================ COMPONENT 1 ================================= -->

    <h4 class="text-center mb-10">Review your order and make payment</h4>
    <div class="row">
      <aside class="col-lg-8">
        <div class="card">
          <h5 class="card-header">Billing Address</h5>
          <div class="card-body">
            <p class="card-text mb-0">{{order.full_name}}</p>
            <p class="card-text mb-0">{{order.full_address}}</p>
            <p class="card-text mb-0">{{order.city}}, {{order.state}}</p>
            <p class="cart-text mb-0">{{order.country}}</p>
            {% if order.order_note %}
            <p class="cart-text mb-0"><b>Order Note:</b> {{order.country}}</p>
            {% endif %}
            <p class="cart-text mb-0">{{order.email}}</p>
            <p class="cart-text mb-0">{{order.phone}}</p>
          </div>
        </div>
        <div class="card">
          <h5 class="card-header">Payment Method</h5>
          <div class="card-body">
            <p class="card-text">PayPal</p>
          </div>
        </div>
        <div class="card">
          <h5 class="card-header">Review Products</h5>
          <div class="card-body">
            <table class="table table-borderless table-shopping-cart">
              <thead class="text-muted">
                <tr class="small text-uppercase">
                  <th scope="col">Product</th>
                  <th scope="col" width="120" class="text-center">Quantity</th>
                  <th scope="col" width="120">Price</th>
                </tr>
              </thead>
              <tbody>
                {% for item in cart_items %}
                <tr>
                  <td>
                    <figure class="itemside align-items-center">
                      <div class="aside">
                        <img src="{{item.product.image.url}}" class="img-sm" />
                      </div>
                      <figcaption class="info">
                        <a href="{{ item.product.get_url }}" class="title text-dark">{{item.product.product_name}}</a>
                        <p class="text-muted small">
                          {% if item.variations.all %}
                          <!-- prettier-ignore -->
                          {% for variation in item.variations.all %}
                          <!-- prettier-ignore -->
                          {{variation.variation_category | capfirst }} : {{variation.variation_value | capfirst }}
                          <br />
                          {% endfor %} {% endif %}
                        </p>
                      </figcaption>
                    </figure>
                  </td>
                  <td class="text-center">
                    <label for="">{{item.quantity}}</label>
                  </td>
                  <td>
                    <div class="price-wrap">
                      <var class="price">${{item.sub_total}}</var>
                      <small class="text-muted"> ${{item.product.price}} each </small>
                    </div>
                    <!-- price-wrap .// -->
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </aside>
      <aside class="col-lg-4">
        <div class="card">
          <div class="card-body">
            <dl class="dlist-align">
              <dt>Total price:</dt>
              <dd class="text-right">${{sub_totals}}</dd>
            </dl>
            <dl class="dlist-align">
              <dt>Tax:</dt>
              <dd class="text-right">${{tax}}</dd>
            </dl>
            <dl class="dlist-align">
              <dt>Total:</dt>
              <dd class="text-right text-dark b">
                <strong>${{grand_totals}}</strong>
              </dd>
            </dl>
            <hr />
            <p class="text-center mb-3">
              <img src="{% static '/images/misc/payments.png' %}" height="26" />
            </p>
            <div id="paypal-button-container">
              <!-- PayPal button will load here -->
            </div>
          </div>
        </div>
      </aside>
    </div>
  </div>
</section>

<script>
  function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== "") {
      const cookies = document.cookie.split(";");
      for (let i = 0; i < cookies.length; i++) {
        const cookie = cookies[i].trim();
        // does this cookie string begin with the name we want?
        if (cookie.substring(0, name.length + 1) === name + "=") {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }

  var amount = "{{grand_totals}}";
  var url = "{% url 'make_payment' %}";
  var csrfToken = getCookie("csrftoken");
  var orderID = "{{order.order_number}}";
  var payment_method = "PayPal";
  const redirect_url = "{% url 'order_complete' %}";

  // render the paypal button into #paypal-button-container
  paypal
    .Buttons({
      style: {
        color: "blue",
        shape: "rect",
        label: "pay",
        height: 40,
      },
      // setup the transaction
      createOrder: function (data, actions) {
        return actions.order.create({
          purchase_units: [
            {
              amount: {
                value: amount,
              },
            },
          ],
        });
      },
      // finalize the transaction
      onApprove: function (data, actions) {
        return actions.order.capture().then(function (details) {
          sendData();
          function sendData() {
            fetch(url, {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": csrfToken,
              },
              body: JSON.stringify({
                orderID,
                transID: details.id,
                payment_method,
                status: details.status,
              }),
            })
              .then((res) => res.json())
              .then((data) => {
                window.location.href = `${redirect_url}?order_number=${data.order_number}&payment_id=${data.payment_id}`;
              });
          }
        });
      },
    })
    .render("#paypal-button-container");
</script>

{% endblock content %}

templates/orders/order_complete.html
{% extends 'base.html' %} {% load static %} {% load custom_filters %} {% block content %}

<div class="container" style="margin-top: 50px">
  <center><i class="fas fa-check-circle" style="font-size: 72px; margin-bottom: 20px; color: #28a745"></i></center>
  <h2 class="text-center">Payment Successful</h2>
  <br />
  <div class="text-center">
    <a href="{% url 'store' %}" class="btn btn-success">Shop more</a>
  </div>
</div>

<div class="container" style="margin: 0 auto; width: 50%; padding: 50px; background: #f1f1f1; margin-top: 50px; margin-bottom: 50px">
  <div class="row invoice row-printable">
    <div class="col-md-12">
      <!-- col-lg-12 start here -->
      <div class="panel panel-default plain" id="dash_0">
        <!-- Start .panel -->
        <div class="panel-body p30">
          <div class="row">
            <!-- Start .row -->
            <div class="col-lg-6">
              <!-- col-lg-6 start here -->
              <div class="invoice-logo" style="font-size: 2rem; color: blue"><h1>E-Mart</h1></div>
            </div>
            <!-- col-lg-6 end here -->
            <div class="col-lg-6">
              <!-- col-lg-6 start here -->
              <div class="invoice-from">
                <ul class="list-unstyled text-right">
                  <li><strong>Invoiced To</strong></li>
                  <li>{{order.full_name}}</li>
                  <li>{{order.full_address}}</li>
                  <li>{{order.city}}, {{order.state}}</li>
                  <li>{{order.country}}</li>
                </ul>
              </div>
            </div>
            <!-- col-lg-6 end here -->
            <div class="col-lg-12">
              <!-- col-lg-12 start here -->
              <div class="invoice-details mt25">
                <div class="well">
                  <ul class="list-unstyled mb0">
                    <li><strong>Order</strong> #{{order.order_number}}</li>
                    <li><strong>Transaction</strong> {{payment.payment_id}}</li>
                    <li><strong>Order Date:</strong> {{order.created_at}}</li>
                    <li><strong>Status:</strong> {{payment.status}}</li>
                  </ul>
                </div>
              </div>

              <div class="invoice-items">
                <div class="table-responsive" style="overflow: hidden; outline: none" tabindex="0">
                  <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th class="per70 text-center">Products</th>
                        <th class="per5 text-center">Qty</th>
                        <th class="per25 text-center">Total</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for product_item in order.orderproduct_set.all %}
                      <tr>
                        <td>
                          {{product_item.product.product_name}}
                          <p class="text-muted small">
                            {% if product_item.variations.all %}
                            <!-- prettier-ignore -->
                            {% for variation in product_item.variations.all %}
                            <!-- prettier-ignore -->
                            {{variation.variation_category | capfirst }} : {{variation.variation_value | capfirst }}
                            <br />
                            {% endfor %} {% endif %}
                          </p>
                        </td>
                        <td class="text-center">{{product_item.quantity}}</td>
                        <td class="text-center">${{product_item.product_price|multiply:product_item.quantity}} USD</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                    <tfoot>
                      <tr>
                        <th colspan="2" class="text-right">Sub Total:</th>
                        <th class="text-center">${{order_sub_total}} USD</th>
                      </tr>
                      <tr>
                        <th colspan="2" class="text-right">Tax:</th>
                        <th class="text-center">${{order.tax}} USD</th>
                      </tr>

                      <tr>
                        <th colspan="2" class="text-right">Grand Total:</th>
                        <th class="text-center">${{order.order_total}} USD</th>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </div>
              <div class="invoice-footer mt25">
                <p class="text-center">Thank you for shopping with us!</p>
              </div>
            </div>
            <!-- col-lg-12 end here -->
          </div>
          <!-- End .row -->
        </div>
      </div>
      <!-- End .panel -->
    </div>
    <!-- col-lg-12 end here -->
  </div>
</div>
{% endblock content %}

templates/orders/order_received_email.html
{% autoescape off %}

<p>Hi {{user.first_name}},</p>

<p>Your order has been received</p>

<p>Order Number: {{order.order_number}}</p>
{% endautoescape %}